### PR TITLE
Add BCH Gurus metadata to otr.cash registry

### PR DESCRIPTION
**Pull request by bchguru**
# New Listing: `GURU`

- Identity Name: `BCH Gurus`
- Authbase: `f54ce0297a4017cc922aacde5f7abe7a8397a1058b879f5eb9e2a643d4ec2301`

## Evidence Linking Authbase to Identity

- **Select one**:
  - [x] **Direct evidence**: a [chain-resolved registry](https://cashtokens.org/docs/bcmr/chip#chain-resolved-registries) at the authhead provides substantially equivalent metadata for this authbase. The Authhead TXID is provided below:
  - [ ] **Indirect evidence**: the identity is [burned](https://cashtokens.org/docs/bcmr/chip#burned-identities) or provably locked within a covenant, so the authbase can safely be linked using indirect evidence. Details and two or more corroborating, third party-archived URLs of reputable sources vouching for this association are provided below:
 
Authhead TXID: `7f970e6b92a926df1251466611105f6775520487b957c2fc07191453b027ad17`

## Evidence Linking Identity to Authbase

The subdomain [nfts.bch.guru](https://nfts.bch.guru/) contains the tokenId for the Gurus in the FAQ section under security. There have been archive.org snapshots on the launch of the nft sale & after the 1st wave completing.

Archived URL(s):  https://web.archive.org/web/20230601131857/https://nfts.bch.guru/
https://web.archive.org/web/20230620100043/https://nfts.bch.guru/

## Evidence Linking Authbase to Categories

- **Select one**:
  - [x] Token `category` is equal to the authbase for all [Identity Snapshots](https://cashtokens.org/docs/bcmr/chip#identity-snapshots).
  - [ ] Evidence is provided for differing `category` values below:

## Substantiation of Other Claims

- **Select one**:
  - [x] The submission (esp. the `description`) includes no claims requiring substantiation.
  - [ ] The claims in this submission can be corroborated with the following evidence:

# Checklist

- [x] I have reviewed the [OpenTokenRegistry inclusion criteria](https://otr.cash/docs/list#inclusion-criteria), and this listing can be included in the registry.
- [ ] The listing completes all required fields:
  - **`name`**
    - [x] Objective, authoritative, and neutral tone
    - [x] No longer than 20 characters; exceptions may be allowed for existing legal names (please provide evidence above including the jurisdiction(s) in which the legal name is established).
  - **`description`**
    - [x] Objective, authoritative, and neutral tone
    - [x] Descriptions is appropriate for use in user interfaces without a disclaimer by unaffiliated, neutral, third parties (wallets, block explorers, exchanges, etc.); no exclamations, calls to action, or disputable statements.
    - [x] All claims are substantiated above.
  - **`token` information** (if applicable)
    - [x] Token `category` is defined.
    - [x] If fungible tokens exist for the `category`, `decimals` is defined.
    - **`symbol`**
      - [x] Globally-unique base symbol, including among assets not listed in OpenTokenRegistry.
      - [x] Valid symbol (regular expression: `/^[A-Z0-9]+[-A-Z0-9]*$/`)
      - [ ] Appropriate minimum length (For new, primarily-fungible base symbols: minimum of 4 characters; non-fungible base symbols: minimum of 6 characters; see [Symbol Length Recommendations](https://cashtokens.org/docs/bcmr/chip/#symbol-length-recommendations))
      - [x] No longer than 13 characters for base symbols
      - [x] No longer than 26 characters for full symbols
  - **`uris.icon`**
    - [x] Uses IPFS (`ipfs://`)
    - [x] Either `SVG` format OR 400px by 400px `AVIF`, `WebP`, or `PNG`
  - **`uris.web`**
    - [x] Domain name is owned by the issuing project or organization
    - [x] Either `HTTPS` protocol OR ongoing activity demonstrated via optional URI identifiers (described in [Substantiation of Other Claims](#substantiation-of-other-claims))
  - [x] Includes relevant historical information in previous snapshots OR this token has never been rebranded, redenominated, or reissued
  - [x] All static data (images, animations, videos, binary files, etc.) uses `IPFS` to ensure file integrity (`ipfs://...`).

## Additional Notes

The only requirement not met is the 6 character minimum for NFTs from the symbol length recommendations. If necessary the symbol can be changed from `GURU `to `BCH-GURU` with the next authchain update.

It was confirmed beforehand that the size of the PR would not be a problem.

### CODE REVIEW

**Comment by bitjson** [comment]
Thanks for the PR @bchguru! Verified all evidence, looks great, thanks for the attention to detail!

Metadata is unchanged from the original publication at `13e44d46044deeb677854165b57d1070ccb3ccdd1e0ca9e81afb7e8966d51333`. (Note to future reviewers: the current authhead is `7f970e6b92a926df1251466611105f6775520487b957c2fc07191453b027ad17` and doesn't attest to any metadata, but @bchguru is clearly not recovering from a hack, and in any case, the issued NFTs are not expected by users to have changing metadata.)

> The only requirement not met is the 6 character minimum for NFTs from the symbol length recommendations. If necessary the symbol can be changed from `GURU `to `BCH-GURU` with the next authchain update.

The `GURU` ticker symbol would also conflict with `TSX:GURU` (`Guru Organic Energy Corp`), so if you're willing to clarify it, that would be great! Also, no need to update the authchain before this is merged, we've already proven the link between identity and authbase above.

[Base symbols must be alphanumeric](https://cashtokens.org/docs/bcmr/chip/#ticker-symbol-selection) since they're the portion of the symbol that occurs before any hyphens (`-`); maybe just dropping that hyphen works for you, base symbol `BCHGURU`? 

(For anyone following along, longer symbols make a lot of sense for NFT collections vs fungible tokens, [discussion summarized here](https://cashtokens.org/docs/bcmr/chip/#symbol-length-recommendations). Also notable, I'm not sure how much NFT ticker symbols will be used for this collection anyways: the NFT commitment numbers are binary encoded rather than VM number encoded, so [rendered ticker symbols](https://cashtokens.org/docs/bcmr/chip/#nft-ticker-symbols) don't always correspond to the numbering assigned via each NFT's `name`. I imagine most interfaces will probably just use `name` in this case.)

Anyways, just let me know if `BCHGURU` works or if you'd prefer some other symbol, and otherwise this is ready to merge 🚀

**Comment by bitjson** [comment]
(@A60AB5450353F40E when you get a chance, if you could be the second reviewer here that'd be great!)

**Comment by bchguru** [comment]
Thanks for the quick review!  
`BCHGURU` as symbol works!

**Review by bitjson — APPROVED** [review]

**Comment by bitjson** [comment]
Updated! Just needs a second approval now @A60AB5450353F40E

**Comment by A60AB5450353F40E** [comment]
lgtm

**Review by A60AB5450353F40E — APPROVED** [review]

**Pull request merged**
