### PR TITLE
add Microfi Free Flow

### PR DESCRIPTION
**Pull request by mazetoken**

### CODE REVIEW

**Comment by BiWinBi** [comment]
This project is great, free for everyone!

**Comment by bitjson** [comment]
Hello – this PR is missing the [pull request template](https://github.com/OpenTokenRegistry/otr.cash/blob/master/.github/pull_request_template.md) – please edit your initial comment to fill out that form. (There are a number of issues that may help to resolve.)

On your description specifically: please see the `Emerald DAO U23` entry for an example of an excellent description: `A series of 2000 keycard NFTs which entitle each holder to a unique, on-chain Emerald DAO safebox holding at least 0.101 BCH. [...]`. Notice that the description is asset-first, and succinctly describes the relevance to the end user. A [more complete reference is here](https://otr.cash/docs/list/#description).

As a general rule, most descriptions do not need to mention "CashTokens", "Bitcoin Cash Blockchain", or issuance details unless they are relevant to the user. (In this case, issuance is centralized and non-deterministic, so I think those details can be excluded?)

**Comment by mazetoken** [comment]
Good point. I will try to fit into the template and change the description. Thank you

**Comment by mazetoken** [comment]
I realized that OTR requires a 4-character token symbol, but mine is 3-character and I'm not going to change it because the token is already registered here https://dtif.org/token-registry-search/
I assume my token can’t be listed in OTR, so I’ll close PR. Thanks for your time

**Pull request closed without merging**
