### PR TITLE
Add FoldingCash (FLDCH) token to registry

### PR DESCRIPTION
**Pull request by StrungSafe**
# New Listing: `FLDCH` 

- Identity Name: `FoldingCash`
- Authbase: `583f4c8daeb660676710e0c1bb6820422f238fb9cf206ed8c008b7db89e0872c`

## Evidence Linking Authbase to Identity

- **Select one**:
  - [x] **Direct evidence**: a [chain-resolved registry](https://cashtokens.org/docs/bcmr/chip#chain-resolved-registries) at the authhead provides substantially equivalent metadata for this authbase. The Authhead TXID is provided below: 583f4c8daeb660676710e0c1bb6820422f238fb9cf206ed8c008b7db89e0872c
  - [ ] **Indirect evidence**: the identity is [burned](https://cashtokens.org/docs/bcmr/chip#burned-identities) or provably locked within a covenant, so the authbase can safely be linked using indirect evidence. Details and two or more corroborating, third party-archived URLs of reputable sources vouching for this association are provided below:

## Evidence Linking Identity to Authbase

Archived URL(s):

https://blockchair.com/bitcoin-cash/transaction/583f4c8daeb660676710e0c1bb6820422f238fb9cf206ed8c008b7db89e0872c
https://blockchair.com/bitcoin-cash/transaction/0adb865ee9cc3038de87fba682e6cd361414edc9acff0da2fd0690d75341c640

## Evidence Linking Authbase to Categories

- **Select one**:
  - [x] Token `category` is equal to the authbase for all [Identity Snapshots](https://cashtokens.org/docs/bcmr/chip#identity-snapshots).
  - [ ] Evidence is provided for differing `category` values below:

## Substantiation of Other Claims

- **Select one**:
  - [x] The submission (esp. the `description`) includes no claims requiring substantiation.
  - [ ] The claims in this submission can be corroborated with the following evidence:

# Checklist

- [x] I have reviewed the [OpenTokenRegistry inclusion criteria](https://otr.cash/docs/list#inclusion-criteria), and this listing can be included in the registry.
- [x] The listing completes all required fields:
  - **`name`**
    - [x] Objective, authoritative, and neutral tone
    - [x] No longer than 20 characters; exceptions may be allowed for existing legal names (please provide evidence above including the jurisdiction(s) in which the legal name is established).
  - **`description`**
    - [x] Objective, authoritative, and neutral tone
    - [x] Descriptions is appropriate for use in user interfaces without a disclaimer by unaffiliated, neutral, third parties (wallets, block explorers, exchanges, etc.); no exclamations, calls to action, or disputable statements.
    - [x] All claims are substantiated above.
  - **`token` information** (if applicable)
    - [x] Token `category` is defined.
    - [x] If fungible tokens exist for the `category`, `decimals` is defined.
    - **`symbol`**
      - [x] Globally-unique base symbol, including among assets not listed in OpenTokenRegistry.
      - [x] Valid symbol (regular expression: `/^[A-Z0-9]+[-A-Z0-9]*$/`)
      - [x] Appropriate minimum length (For new, primarily-fungible base symbols: minimum of 4 characters; non-fungible base symbols: minimum of 6 characters; see [Symbol Length Recommendations](https://cashtokens.org/docs/bcmr/chip/#symbol-length-recommendations))
      - [x] No longer than 13 characters for base symbols
      - [x] No longer than 26 characters for full symbols
  - **`uris.icon`**
    - [x] Uses IPFS with a v1 CID. To convert a v0 CID (begins with `Qm...`), try `dweb.link`. For example, `QmcNL1KcVmiDtwJe8WokrnzYeoHirsz1sNxNojncsxyb2p` is a v0 CID. It can be viewed at `https://dweb.link/ipfs/QmcNL1KcVmiDtwJe8WokrnzYeoHirsz1sNxNojncsxyb2p`, which redirects to a subdomain equal to the v1 CID: `https://bafybeigqogqx3n4cldk6nizl5vihopi2dkgvw4yqamc5rhleyqu25soe4e.ipfs.dweb.link/`. The correct URI for this icon is: `ipfs://bafybeigqogqx3n4cldk6nizl5vihopi2dkgvw4yqamc5rhleyqu25soe4e`.
    - [x] Either `SVG` format OR 400px by 400px `AVIF`, `WebP`, or `PNG`
  - **`uris.web`**
    - [x] Domain name is owned by the issuing project or organization
    - [x] Either `HTTPS` protocol OR ongoing activity demonstrated via optional URI identifiers (described in [Substantiation of Other Claims](#substantiation-of-other-claims))
  - [x] Includes relevant historical information in previous snapshots OR this token has never been rebranded, redenominated, or reissued
  - [x] All static data (images, animations, videos, binary files, etc.) uses `IPFS` with v1 CIDs to ensure file integrity (e.g. `ipfs://ba...`).

### CODE REVIEW

**Comment by georgedonnelly** [comment]
Hey thanks for your PR. Here is some feedback:

- the icon is expected to be 400 x 400 px. https://otr.cash/docs/list
- the icon should also be hosted on IPFS.
- it's expected that somewhere on the web page that is linked to that it will include a statement such as: "BCH XYZ token: category (ideally with a link to tokenexplorer.cash or an explorer etc.)" in order to show users that the website actively claims the token as related to the website.
- A more descriptive name is recommended.
- I don't think there is an image field in the spec? Or at least it is redundant.
- A more detailed description is also recommended.

Full listing guidelines are here: https://otr.cash/docs/list. Please read through them. Thanks! I look forward to merging your token in once the listing requirements are met.

Note to self, the category for your token is: 0adb865ee9cc3038de87fba682e6cd361414edc9acff0da2fd0690d75341c640

**Comment by StrungSafe** [comment]
Thank you for your feedback, 

I'm making the updates but will take me about a week or two to get the on-chain meta data updated. Will update here when PR is ready for further review. Thank you

**Comment by StrungSafe** [comment]
I've updated the onchain metadata, the updated authhead is here
`79c735662171b9c043adbdf83cc9c9b3509d192a426ea6a3507badde3d3a4c1e`

I believe I've corrected all the other issues too

Ready for review again

**Comment by georgedonnelly** [comment]
Hey, thanks! Can you make the icon 400 x 400? Just center the image there and the background can be transparent ideally. Otherwise I think it's fine.

**Comment by StrungSafe** [comment]
my apologies, missed committing the updated icon
new authhead `dc98c3292e0699cfc9f1c5ac0ab640d6adb96f53ad38093a18c2893bfe135385`
should be good now 🤞🏽

**Comment by georgedonnelly** [comment]
Looks good! Thanks!

**Review by georgedonnelly — APPROVED** [review]

**Comment by georgedonnelly** [comment]
I thought I could approve this myself but not the case. Please ping bitjson on Telegram and ask him for his review.

**Comment by bitjson** [comment]
I'm here! Thank you for the detailed review @georgedonnelly, and thanks for the contribution @StrungSafe.

Verified latest authhead from authbase `0adb865ee9cc3038de87fba682e6cd361414edc9acff0da2fd0690d75341c640 `: `dc98c3292e0699cfc9f1c5ac0ab640d6adb96f53ad38093a18c2893bfe135385`, OP_RETURN references: `https://folding.cash/.well-known/bitcoin-cash-metadata-registry.json`.

Archived:
- https://web.archive.org/web/20240904205830/https://folding.cash/.well-known/bitcoin-cash-metadata-registry.json & https://archive.is/nFBqK
- https://web.archive.org/web/20240904205057/https://folding.cash/ & https://archive.is/ilz2K
- https://web.archive.org/web/20240904205146/https://old.reddit.com/r/FoldingCash/ & https://archive.is/lty4P

I'm the second review, so merging 🚀

**Review by bitjson — COMMENTED** [review]
ACK

**Pull request merged**
