### PR TITLE
Add BLDC token

### PR DESCRIPTION
**Pull request by 7sxnc**
I'm trying to create this pull request:

# New Listing: `BLDC` 

- Identity Name: Limones Digital Coin
- Authbase: 671b3b66b3d8c38883cf74e8028968723c3345d695adfb42607ca5b0befdbb96

## Evidence Linking Authbase to Identity

- **Select one**:
  - [X] **Direct evidence**: a [chain-resolved registry](https://cashtokens.org/docs/bcmr/chip#chain-resolved-registries) at the authhead provides substantially equivalent metadata for this authbase. The Authhead TXID is provided below:
  - [ ] **Indirect evidence**: the identity is [burned](https://cashtokens.org/docs/bcmr/chip#burned-identities) or provably locked within a covenant, so the authbase can safely be linked using indirect evidence. Details and two or more corroborating, third party-archived URLs of reputable sources vouching for this association are provided below:

## Evidence Linking Authbase to Categories

- **Select one**:
  - [X] Token `category` is equal to the authbase for all [Identity Snapshots](https://cashtokens.org/docs/bcmr/chip#identity-snapshots).
  - [ ] Evidence is provided for differing `category` values below:

 Proof: https://explorer.bitcoinunlimited.info/tx/c11826c6535ecae051d250ff827fef262999172a1a58088b7dcfa605d30d583a

## Substantiation of Other Claims

- **Select one**:
  - [X] The submission (esp. the `description`) includes no claims requiring substantiation.
  - [ ] The claims in this submission can be corroborated with the following evidence:

# Checklist

- [X] I have reviewed the [OpenTokenRegistry inclusion criteria](https://otr.cash/docs/list#inclusion-criteria), and this listing can be included in the registry.
- [X] The listing completes all required fields:
  - **`name`**
    - [X] Objective, authoritative, and neutral tone
    - [X] No longer than 20 characters; exceptions may be allowed for existing legal names (please provide evidence above including the jurisdiction(s) in which the legal name is established).
  - **`description`**
    - [X] Objective, authoritative, and neutral tone
    - [X] Descriptions is appropriate for use in user interfaces without a disclaimer by unaffiliated, neutral, third parties (wallets, block explorers, exchanges, etc.); no exclamations, calls to action, or disputable statements.
    - [X] All claims are substantiated above.
  - **`token` information** (if applicable)
    - [X] Token `category` is defined.
    - [X] If fungible tokens exist for the `category`, `decimals` is defined.
    - **`symbol`**
      - [X] Globally-unique base symbol, including among assets not listed in OpenTokenRegistry.
      - [X] Valid symbol (regular expression: `/^[A-Z0-9]+[-A-Z0-9]*$/`)
      - [X] Appropriate minimum length (For new, primarily-fungible base symbols: minimum of 4 characters; non-fungible base symbols: minimum of 6 characters; see [Symbol Length Recommendations](https://cashtokens.org/docs/bcmr/chip/#symbol-length-recommendations))
      - [X] No longer than 13 characters for base symbols
      - [X] No longer than 26 characters for full symbols
  - **`uris.icon`**
    - [X] Uses IPFS with a v1 CID. To convert a v0 CID (begins with `Qm...`), try `dweb.link`. For example, `bafybeifv5l6foaqrxeux4dl7mj55d4a4lsthbrsyba3v6yqtarzbxcmn2m` is a v0 CID. It can be viewed at `https://d391b93f5f62d9c15f67142e43841acc.ipfscdn.io/ipfs/bafybeifv5l6foaqrxeux4dl7mj55d4a4lsthbrsyba3v6yqtarzbxcmn2m/a21966af10fabce599678eb258e69158.png`, which redirects to a subdomain equal to the v1 CID: `https://d391b93f5f62d9c15f67142e43841acc.ipfscdn.io/`. The correct URI for this icon is: `ipfs://QmaanKpq3bsHUrpJuASynqDurDeQbTYz6v35BLaD2BDmzS/a21966af10fabce599678eb258e69158.png`.
    - [X] Either `SVG` format OR 400px by 400px `AVIF`, `WebP`, or `PNG`
  - **`https://limonia.org`**
    - [X] Domain name is owned by the issuing project or organization
    - [X] Either `HTTPS` protocol OR ongoing activity demonstrated via optional URI identifiers (described in [Substantiation of Other Claims](#substantiation-of-other-claims))
  - [X] Includes relevant historical information in previous snapshots OR this token has never been rebranded, redenominated, or reissued
  - [X] All static data (images, animations, videos, binary files, etc.) uses `IPFS` with v1 CIDs to ensure file integrity (e.g. `ipfs://ba...`).

### CODE REVIEW

**Review by georgedonnelly — CHANGES_REQUESTED** [review]
Hi. 

Generally speaking, it is best not to create multiple PRs for the same code merge request.

Thanks for addressing some of my feedback from PR #16, however you don't seem to have addressed comments 1, 2, 4, and 6.

Standing by.

**Comment by georgedonnelly** [comment]
Description looks better! Still no chain-resolved metadata for b1899ba19c167d4ea9dcc64516b6295cdd7616b179b4146f461aacc623e14be6. Still no statement on the website?

**Comment by 7sxnc** [comment]
I added to website https://limonia.org/about-ldc

**Comment by 7sxnc** [comment]
And i added to https://limonia.org/.well-known/bitcoin-cash-metadata-registry.json

**Comment by georgedonnelly** [comment]
Issue 2 remains: You appear to have no on-chain BCMR. This would be good to have.

**Comment by 7sxnc** [comment]
> Issue 2 remains: You appear to have no on-chain BCMR. This would be good to have.

How to have on-chain BCMR?

**Comment by 7sxnc** [comment]
> Issue 2 remains: You appear to have no on-chain BCMR. This would be good to have.

Check this new

https://limonia.org/.well-known/registry.json

**Comment by georgedonnelly** [comment]
That is called a DNS-resolved registry.

You can request more personalized help in the CashToken Devs group, where you are very welcome to ask as many questions as you like!

https://t.me/cashtoken_devs

**Comment by 7sxnc** [comment]
Ok, thanks i will provide.

**Comment by 7sxnc** [comment]
Check https://bafkreiemdnzjtdzoukh55zbux7g2w6oe5wz5nt36slhgd7pudlpucq2p24.ipfs.nftstorage.link

**Comment by georgedonnelly** [comment]
Great work in updating your authead! It looks good to me. Now, you just need to update your PR here to match your new chain-resolved BCMR.

**Comment by 7sxnc** [comment]
> Great work in updating your authead! It looks good to me. Now, you just need to update your PR here to match your new chain-resolved BCMR.

Check new commit

**Review by georgedonnelly — APPROVED** [review]
It's now looking good. I am approving. Now you just need to wait for someone with write access to review your PR. Great work!

**Comment by 7sxnc** [comment]
Ok, thanks.

**Comment by bitjson** [comment]
Thanks for your work here @7sxnc and @georgedonnelly!

I fixed the merge conflicts and JSON errors, then I re-pinned your icon without the containing folder (still using nft.storage), and corrected the `icon` URI to use the `ifps://` protocol. I also modified the second sentence of your description to avoid making a specific claim about usability (`It is intended for use in` rather than `Its use can be directed towards`).

@7sxnc please let me know if you're OK with this changes, and I can merge the PR. 🚀

```json
"b1899ba19c167d4ea9dcc64516b6295cdd7616b179b4146f461aacc623e14be6": {
      "2024-01-17T18:26:16.811Z": {
        "name": "Limones Digital Coin",
        "description": "A fiduciary stablecoin with the aim of facilitating financial transactions within the Federation of Limonia and intermediating the exchange of foreign currencies. It is intended for use in online shopping, investments, loans, and digital network e-commerce services.",
        "token": {
          "category": "b1899ba19c167d4ea9dcc64516b6295cdd7616b179b4146f461aacc623e14be6",
          "decimals": 2,
          "symbol": "BLDC"
        },
        "uris": {
          "icon": "ipfs://bafkreiaxleys6twenyiam2cztzrw7fewadz44cuvb5eozcro2cs2byyaqe",
          "web": "https://limonia.org",
          "support": "we@limonia.org",
          "twitter": "https://twitter.com/govlimonia",
          "chat": "https://discord.gg/CB5xRfWC5j"
        }
      }
    },
```

**Comment by 7sxnc** [comment]
It's okay

**Pull request merged**
