### PR TITLE
Please add Bismuth Win Bi Token(BWBT)

### PR DESCRIPTION
**Pull request by BiWinBi**
# New Listing: `BWBT` 

- Identity Name: `Bismuth Win Bi Token`
- Authbase: `36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797`

## Evidence Linking Authbase to Identity

- **Select one**:
  - [x] **Direct evidence**: a [chain-resolved registry](https://cashtokens.org/docs/bcmr/chip#chain-resolved-registries) at the authhead provides substantially equivalent metadata for this authbase. The Authhead TXID is provided below:
  - [ ] **Indirect evidence**: the identity is [burned](https://cashtokens.org/docs/bcmr/chip#burned-identities), so the authbase can safely be linked using indirect evidence. Two or more corroborating, third party-archived URLs of reputable sources vouching for this association are provided below:

If "Direct evidence" is checked, provide the Authhead TXID here.
`b71e9f80e5c8e065efcad92c876438b55e204e82c250be8959d4d87982ed89e6`

If "Indirect evidence" is checked, provide at least two third-party archived URLs (archive.org, archive.is, etc.) of reputable sources vouching for this association. If the archiving service does not include the original URL in the archived URLs (i.e. it also shortens URLs), please also provide the original URL. -->

## Evidence Linking Identity to Authbase

Archived URL(s):

## Evidence Linking Authbase to Categories

- **Select one**:
  - [x] Token `category` is equal to the authbase for all [Identity Snapshots](https://cashtokens.org/docs/bcmr/chip#identity-snapshots).
  - [ ] Evidence is provided for differing `category` values below:

## Substantiation of Other Claims

- **Select one**:
  - [x] The submission (esp. the `description`) includes no claims requiring substantiation.
  - [ ] The claims in this submission can be corroborated with the following evidence:

# Checklist

- [x] I have reviewed the [OpenTokenRegistry inclusion criteria](https://otr.cash/docs/list#inclusion-criteria), and this listing can be included in the registry.
- [x] The listing completes all required fields:
  - **`name`**
    - [x] Objective, authoritative, and neutral tone
    - [x] No longer than 20 characters; exceptions may be allowed for existing legal names (please provide evidence above including the jurisdiction(s) in which the legal name is established).
  - **`description`**
    - [x] Objective, authoritative, and neutral tone
    - [x] Descriptions is appropriate for use in user interfaces without a disclaimer by unaffiliated, neutral, third parties (wallets, block explorers, exchanges, etc.); no exclamations, calls to action, or disputable statements.
    - [x] All claims are substantiated above.
  - **`token` information** (if applicable)
    - [x] Token `category` is defined.
    - [x] If fungible tokens exist for the `category`, `decimals` is defined.
    - **`symbol`**
      - [x] Globally-unique base symbol, including among assets not listed in OpenTokenRegistry.
      - [x] Valid symbol (regular expression: `/^[A-Z0-9]+[-A-Z0-9]*$/`)
      - [x] Appropriate minimum length (for new assets: 4 or more characters for primarily fungible base symbols, 6 or more characters for primarily non-fungible base symbols)
      - [x] No longer than 13 characters for base symbols
      - [x] No longer than 26 characters for full symbols
  - **`uris.icon`**
    - [x] Uses IPFS (`ipfs://`)
    - [x] Either `SVG` format OR 400px by 400px `AVIF`, `WebP`, or `PNG`
  - **`uris.web`**
    - [x] Domain name is owned by the issuing project or organization
    - [x] Either `HTTPS` protocol OR ongoing activity demonstrated via optional URI identifiers (described in [Substantiation of Other Claims](#substantiation-of-other-claims))
  - [x] Includes relevant historical information in previous snapshots OR this token has never been rebranded, redenominated, or reissued
  - [x] All static data (images, animations, videos, binary files, etc.) uses `IPFS` to ensure file integrity (`ipfs://...`).

### CODE REVIEW

**Comment by bitjson** [comment]
Thanks for opening a PR! Some initial thoughts:

- **Needs a clearer description** – a great description is asset-first, explaining what it means to a user if this asset unexpectedly ends up in their wallet. Ideally, the first sentence should be a complete summary, and the following sentences within the first paragraph simply expand on that initial sentence. Any number of following paragraphs may continue to provide further information, with the most important information appearing first. Please review other descriptions in the registry for examples.
- **Ticker symbol conflicts with existing asset(s)**: `NASDAQ:BWB` (`Bridgewater Bancshares Inc`); `XETRA:BWB` (`Baader Bank AG`).
    - Neutral wallets, exchanges, block explorers, and other service providers rely on OpenTokenRegistry to safeguard the symbols and data they render to users, so adding new listings which conflict with existing asset symbols in the wider marketplace might prevent others from relying on OpenTokenRegistry's data. Please note, OpenTokenRegistry has no control over symbol "assignments" in the wider marketplace; we do not have the power to unilaterally grant conflicting symbols to any particular party. In cases of long-standing disputes over a particular symbol (e.g. the same symbol has been used to refer to different assets by good-faith actors across multiple international markets), OpenTokenRegistry may be forced to prefix one or both symbols for clarity (e.g. `NYSE-DTE`, `XETRA-DTE`).
    - For new assets, we recommend reviewing the [BCMR Symbol Length Recommendations](https://cashtokens.org/docs/bcmr/chip#symbol-length-recommendations).
    - If rebranding to a unique symbol is impossible, please provide multiple examples of well-known, neutral institutions who recognize this asset using the contentious symbol (e.g. exchanges, brokers, custodians, data providers, etc.) and recommend a prefix for the listing in OpenTokenRegistry (e.g. `NYSE-`, `NASDAQ-`, `XETRA-`, `PAR-`, etc.)
- **`uris.icon` does not resolve** – we are currently unable to resolve `ipfs://QmcBcbsWuhvrpZnxBFsTuXsEmsJgYXyppQXjtnC6qKQUXt` over IPFS. Consider using a pinning service like [nft.storage](https://nft.storage/).

**Comment by BiWinBi** [comment]
Thanks @bitjson , I will revise the BCMR immediately.

**Comment by A60AB5450353F40E** [comment]
I verified last BCMR TX was [`35a4c1e5f197b1701960f60ee0ec3a01e53c0735471953260207a88f301daca6`](https://blockchair.com/bitcoin-cash/transaction/35a4c1e5f197b1701960f60ee0ec3a01e53c0735471953260207a88f301daca6), but authchain has been extended in the meantime. Are you still in control of the authchain? Current authhead is at TXID [`459b782fa9f5e64fd27ab6e7472153d1d8a57aadc16c31752a4aa89f28e34e8a`](https://blockchair.com/bitcoin-cash/transaction/459b782fa9f5e64fd27ab6e7472153d1d8a57aadc16c31752a4aa89f28e34e8a), do you own the output 0 of that transaction?

Suggestion for token-first / bare facts description, change:

>Bismuth Win Bi Token is a new Cashtokens created on the May 15, 2023, which provides an on-chain resolution on Bitcoin Cash. \n The Cashtokens used to be fungible tokens on SmartBCH, and issued with the total amount 21000000 and decimals 8 which pays a tribute to Bitcoin Cash .\n This token serves as coupons and points on the e-commerce shop Bismuth Shed.\n The logo represents the bismuth crystals with an abstract view.

to:

>Bismuth Win Bi Token serves as coupons and points on the e-commerce shop Bismuth Shed.\n\nOn Bitcoin Cash blockchain, the token has been created on May 15th 2023, with maximum supply of 21,000,000 BWBT, and divisible to 8 decimals.\n\nAt time of creation on Bitcoin Cash network, the token also existed on BNB and SmartBCH blockchain, as contract 0x2e1da8eb00cd1ff9b201f51e3705d87e06313881 on both.

**Comment by BiWinBi** [comment]
@A60AB5450353F40E Thanks for your help! I am not very fluent in English, so maybe some details of description are not objective enough. I will change the description as your advice. 

I am the owner of address
[qq8zecmysee9c9fvjasg9w2taeh0vj5hhqxve727dg](https://blockchair.com/bitcoin-cash/address/qq8zecmysee9c9fvjasg9w2taeh0vj5hhqxve727dg)
Which is the sender of
[459b782fa9f5e64fd27ab6e7472153d1d8a57aadc16c31752a4aa89f28e34e8a](https://blockchair.com/bitcoin-cash/transaction/459b782fa9f5e64fd27ab6e7472153d1d8a57aadc16c31752a4aa89f28e34e8a)
So please check if I own the output 0, thank you very much!

photo_2023-05-31_15-22-22

**Comment by A60AB5450353F40E** [comment]
>So please check if I own the output 0, thank you very much!

Ahh I see you sent from that address to pat's swap contract, which means you'll get the authchain back once someone fills the order or you cancel the particular order (because next output0 will again go to your address), so if you want to keep the authchain, you gotta freeze the UTXO in your wallet (Electron Cash supports this) or just send it to another wallet and store safely.

**Comment by BiWinBi** [comment]
Thanks @A60AB5450353F40E , let me try to do this on Electron Cash.

**Comment by A60AB5450353F40E** [comment]
>Evidence Linking Identity to Authbase

Made a snapshot of your site, just adding here for reference and as back-validation from the associated site: https://web.archive.org/web/20230531075526/https://bismuthshed.com/bismuth-win-bi-bwb-trading-now/

LGTM now, wdyt @bitjson

**Comment by A60AB5450353F40E** [comment]
Also, ipfs cid again seems not to load, but I see one older link works, is this the icon you want?

https://gateway.pinata.cloud/ipfs/bafybeicizft5gbfu5nuq4o3iwjoad6g74ubobbvovtlgket2zgzxhrfewe

**Comment by A60AB5450353F40E** [comment]
Icon loads from both here: https://ipfs.pat.mn/ipfs/QmcBcbsWuhvrpZnxBFsTuXsEmsJgYXyppQXjtnC6qKQUXt and here: https://ipfs.pat.mn/ipfs/bafybeignwma3smjzfgmuj252h7i3dwwuu654x6bof3mmqli267mbrrhsim

also on pinata now https://gateway.pinata.cloud/ipfs/bafybeignwma3smjzfgmuj252h7i3dwwuu654x6bof3mmqli267mbrrhsim

**Comment by BiWinBi** [comment]
Yes, really appreciate Pinata still works, maybe I should upload to the nft.storage

> Also, ipfs cid again seems not to load, but I see one older link works, is this the icon you want?
> 
> https://gateway.pinata.cloud/ipfs/bafybeicizft5gbfu5nuq4o3iwjoad6g74ubobbvovtlgket2zgzxhrfewe

**Comment by A60AB5450353F40E** [comment]
It's ok, looks like at least pinata is mirroring [`bafybeignwma3smjzfgmuj252h7i3dwwuu654x6bof3mmqli267mbrrhsim`](https://gateway.pinata.cloud/ipfs/bafybeignwma3smjzfgmuj252h7i3dwwuu654x6bof3mmqli267mbrrhsim) now

**Comment by BiWinBi** [comment]
The icon on nft.storage :
ipfs://bafkreib5fkmfd3frpjq7unumtj3ughcdxen4bcmmq3vqrp7bxzk626zeia/

**Review by A60AB5450353F40E — APPROVED** [review]
lgtm

**Comment by BiWinBi** [comment]
Hello, @bitjson . How about this request now?

**Comment by bitjson** [comment]
Thanks for your work on this @BiWinBi and @A60AB5450353F40E! The technical elements look solid; the description is already much clearer too!

> Bismuth Win Bi Token serves as coupons and points on the e-commerce shop Bismuth Shed.
>
> On Bitcoin Cash blockchain, the token has been created on May 15th 2023, with maximum supply of 21,000,000 BWBT, and divisible to 8 decimals.
>
> At time of creation on Bitcoin Cash network, the token also existed on BNB and SmartBCH blockchain, as contract 0x2e1da8eb00cd1ff9b201f51e3705d87e06313881 on both.

Initial questions:

- What does `Win Bi` mean or stand for? Given the description, it seems like users in the `en` locale would casually describe this as "Bismuth Shed points". Can you clarify the difference?
- This is solely a fungible token category, correct? In what respect are they coupons? In what respect are they points? (What do the points do?) Do they map to some currency value? Is there some formula at which they convert, or some way a holder can otherwise understand the value of their token(s)? Are there legal terms posted on the website? Under what jurisdiction(s) are they enforced?
- Is there some reason to mention the maximum supply? These are centrally issued/redeemed, right? So the unissued supply seems irrelevant, users should only plausibly care about circulating supply?
- The description mentions assets issued on other chains: are those interchangeable? Deprecated, or in simultaneous use? Is there a method by which users can still exchange them? Are these details posted somewhere? (If so, a `uris.migrate` might be valuable!)

**Comment by BiWinBi** [comment]
> Initial questions:

> * What does `Win Bi` mean or stand for? Given the description, it seems like users in the `en` locale would casually describe this as "Bismuth Shed points". Can you clarify the difference?

"Win" means "to win" as its original meaining in English, and "Bi" means coins in Chinese.

> * This is solely a fungible token category, correct? In what respect are they coupons? In what respect are they points? (What do the points do?) Do they map to some currency value? Is there some formula at which they convert, or some way a holder can otherwise understand the value of their token(s)? Are there legal terms posted on the website? Under what jurisdiction(s) are they enforced?

We don't have a formula for this token now. It depends on the market to determine the value. If the holder of BWBT wants to purchase in Bismuth Shed, they will get a discount for at least 1 USD for 10000 BWBT. So we can say the minimum value is 1 USD for 10000 BWBT.

> * Is there some reason to mention the maximum supply? These are centrally issued/redeemed, right? So the unissued supply seems irrelevant, users should only plausibly care about circulating supply?

No particular reason. We pay tribute to the original bitcoin, that's why we choose the total supply 21000000. There is no unissued supply. We only list this token on tapswap.cash, and there only 2000000 BWBT on circulation for now.

> * The description mentions assets issued on other chains: are those interchangeable? Deprecated, or in simultaneous use? Is there a method by which users can still exchange them? Are these details posted somewhere? (If so, a `uris.migrate` might be valuable!)

Sorry, there is no cross-chain bridges between those blockchains now. But the BWB on SmartBCH and BNB Smart Chain are both tradable on their original chains. Please visit [biwinbi.github.io/web/](https://biwinbi.github.io/web/) for the details. 

Thank you very much @bitjson. I can revise the description or add the information to our site asap. Please let me know if there are more questions about the descriptions.

**Comment by BiWinBi** [comment]
> > Initial questions:
> > 
> > * What does `Win Bi` mean or stand for? Given the description, it seems like users in the `en` locale would casually describe this as "Bismuth Shed points". Can you clarify the difference?
"Win" means "to win" as its original meaining in English, and "Bi" means coins in Chinese.
> 
> > * This is solely a fungible token category, correct? In what respect are they coupons? In what respect are they points? (What do the points do?) Do they map to some currency value? Is there some formula at which they convert, or some way a holder can otherwise understand the value of their token(s)? Are there legal terms posted on the website? Under what jurisdiction(s) are they enforced?
We don't have a formula for this token now. It depends on the market to determine the value. If the holder of BWBT wants to purchase in Bismuth Shed, they will get a discount for at least 1 USD for 10000 BWBT. So we can say the minimum value is 1 USD for 10000 BWBT.
> 
> > * Is there some reason to mention the maximum supply? These are centrally issued/redeemed, right? So the unissued supply seems irrelevant, users should only plausibly care about circulating supply?
No particular reason. We pay tribute to the original bitcoin, that's why we choose the total supply 21000000. There is no unissued supply. We only list this token on tapswap.cash ,only 2000000 BWB for now.
> 
> > * The description mentions assets issued on other chains: are those interchangeable? Deprecated, or in simultaneous use? Is there a method by which users can still exchange them? Are these details posted somewhere? (If so, a `uris.migrate` might be valuable!)
Sorry, there is no cross-chain bridges between those blockchains now. But the BWB on SmartBCH and BNB Smart Chain are both exchangeable on its original chains. Please visit [biwinbi.github.io/web/](https://biwinbi.github.io/web/) for the details.
> 
> Thank you very much @bitjson. I can revise the description or add the information to our site asap. Please let me know if there are more questions about the descriptions.

**Comment by BiWinBi** [comment]
Hello, @bitjson . Thanks for the reviews. How about this request now?

**Comment by BiWinBi** [comment]
I changed my authhead TXID

**Comment by BiWinBi** [comment]
Our website updated https://biwinbi.github.io/web/
Hello, @bitjson . Thanks for the reviews. How about this request now?

**Comment by bitjson** [comment]
Happy to review again, did you mean to push a commit with new changes to the description? The above questions don't seem to be resolved in the actual PR yet.

On content: please see the `Emerald DAO U23` entry for an example of an excellent description: `A series of 2000 keycard NFTs which entitle each holder to a unique, on-chain Emerald DAO safebox holding at least 0.101 BCH. [...]`. Notice that the description is asset-first, and succinctly describes the relevance to the end user. A [more complete reference is here](https://otr.cash/docs/list/#description).

As a general rule, most descriptions do not need to mention "CashTokens", "Bitcoin Cash Blockchain", or issuance details unless they are relevant to the user. (In this case, issuance is centralized and non-deterministic, so I think those details can be excluded?)

**Comment by BiWinBi** [comment]
Sure, thanks! @bitjson 
I revised the description as your advices, and added one more site https://biwinbi.github.io/web/ to the web. We have published the minimum value of 10000 BWB for 1 USD on this site, I'm not sure if that's OK.
As you said, the description should be succinct, so I removed the unnecessary parts.

**Comment by bitjson** [comment]
Hi @BiWinBi, this listing looks technically ready, it just needs some clarification on the description ([these questions](https://github.com/OpenTokenRegistry/otr.cash/pull/3#issuecomment-1574316757)). 

Maybe it would be helpful for me to try to summarize as I understand from your posting above and the about page of your website?

A first draft:

`Loyalty points issued by Bismuth Shed, an e-commerce store specializing in bismuth crystals and ores.\n\nBismuth Shed was founded in 2017 and is based in Taipei City, Taiwan. Bismuth Shed also operates an open-air store at Taipei Nangang Exhibition Center.`

Is this accurate so far?

- I excluded discussion of CashTokens, creation date, and maximum supply, as those aren't relevant for a token issued and honored by a specific organization.
- I also didn't mention the price at which you're selling points, since we generally want to keep this content "evergreen". 
- I see you also mentioned `This is equivalent to at least 1 USD and is backed by the team.`. To make that sort of claim in this registry, we'd likely need to frame it in the context of a claim made by your auditor(s) rather than a claim of fact by OTR. For now, I just kept the description simple. 

Hopefully this gets you started, please let me know if I can help clarify anything! There's also [more guidance here on writing a great description](https://otr.cash/docs/list/#description).

**Comment by BiWinBi** [comment]
Hi @bitjson, thanks for the reviews and the draft, but we are a pure e-commerce shop now, and we don't operate an open-air store at Taipei Nangang Exhibition Center. We only offer pickup orders near the exits of Taipei Nangang Exhibition Center Station([MRT Station](https://en.wikipedia.org/wiki/Taipei_Nangang_Exhibition_Center_metro_station))

So the draft still not very accurate, and we don't want change the $BWBT symbol now. A big thank you for you and OTR!

> A first draft:
> 
> `Loyalty points issued by Bismuth Shed, an e-commerce store specializing in bismuth crystals and ores.\n\nBismuth Shed was founded in 2017 and is based in Taipei City, Taiwan. Bismuth Shed also operates an open-air store at Taipei Nangang Exhibition Center.`
> 
> Is this accurate so far?

**Pull request closed without merging**
