### PR TITLE
Please add Bismuth Win Bi Token(BWBT)

### PR DESCRIPTION
**Pull request by BiWinBi**
(Edit by @bitjson: this PR began as https://github.com/OpenTokenRegistry/otr.cash/pull/3)

# New Listing: `BWBT` 

- Identity Name: `Bismuth Win Bi Token`
- Authbase: `36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797`

## Evidence Linking Authbase to Identity

- **Select one**:
  - [x] **Direct evidence**: a [chain-resolved registry](https://cashtokens.org/docs/bcmr/chip#chain-resolved-registries) at the authhead provides substantially equivalent metadata for this authbase. The Authhead TXID is provided below:
  - [ ] **Indirect evidence**: the identity is [burned](https://cashtokens.org/docs/bcmr/chip#burned-identities), so the authbase can safely be linked using indirect evidence. Two or more corroborating, third party-archived URLs of reputable sources vouching for this association are provided below:

If "Direct evidence" is checked, provide the Authhead TXID here.
`779e39ebc1dd539788f69c76dc61019d976be229ad2ecd1103290ae49424ff28:0`

If "Indirect evidence" is checked, provide at least two third-party archived URLs (archive.org, archive.is, etc.) of reputable sources vouching for this association. If the archiving service does not include the original URL in the archived URLs (i.e. it also shortens URLs), please also provide the original URL. -->

## Evidence Linking Identity to Authbase

Archived URL(s):

## Evidence Linking Authbase to Categories

- **Select one**:
  - [x] Token `category` is equal to the authbase for all [Identity Snapshots](https://cashtokens.org/docs/bcmr/chip#identity-snapshots).
  - [ ] Evidence is provided for differing `category` values below:

## Substantiation of Other Claims

- **Select one**:
  - [x] The submission (esp. the `description`) includes no claims requiring substantiation.
  - [ ] The claims in this submission can be corroborated with the following evidence:

# Checklist

- [x] I have reviewed the [OpenTokenRegistry inclusion criteria](https://otr.cash/docs/list#inclusion-criteria), and this listing can be included in the registry.
- [x] The listing completes all required fields:
  - **`name`**
    - [x] Objective, authoritative, and neutral tone
    - [x] No longer than 20 characters; exceptions may be allowed for existing legal names (please provide evidence above including the jurisdiction(s) in which the legal name is established).
  - **`description`**
    - [x] Objective, authoritative, and neutral tone
    - [x] Descriptions is appropriate for use in user interfaces without a disclaimer by unaffiliated, neutral, third parties (wallets, block explorers, exchanges, etc.); no exclamations, calls to action, or disputable statements.
    - [x] All claims are substantiated above.
  - **`token` information** (if applicable)
    - [x] Token `category` is defined.
    - [x] If fungible tokens exist for the `category`, `decimals` is defined.
    - **`symbol`**
      - [x] Globally-unique base symbol, including among assets not listed in OpenTokenRegistry.
      - [x] Valid symbol (regular expression: `/^[A-Z0-9]+[-A-Z0-9]*$/`)
      - [x] Appropriate minimum length (for new assets: 4 or more characters for primarily fungible base symbols, 6 or more characters for primarily non-fungible base symbols)
      - [x] No longer than 13 characters for base symbols
      - [x] No longer than 26 characters for full symbols
  - **`uris.icon`**
    - [x] Uses IPFS (`ipfs://`)
    - [x] Either `SVG` format OR 400px by 400px `AVIF`, `WebP`, or `PNG`
  - **`uris.web`**
    - [x] Domain name is owned by the issuing project or organization
    - [x] Either `HTTPS` protocol OR ongoing activity demonstrated via optional URI identifiers (described in [Substantiation of Other Claims](#substantiation-of-other-claims))
  - [x] Includes relevant historical information in previous snapshots OR this token has never been rebranded, redenominated, or reissued
  - [x] All static data (images, animations, videos, binary files, etc.) uses `IPFS` to ensure file integrity (`ipfs://...`).

### CODE REVIEW

**Comment by BiWinBi** [comment]
Thanks,@bitjson 
I reopened this pull request, for the old one had too many conflicts

**Comment by BiWinBi** [comment]
Our new discounts for BWBT holder
https://bismuthshed.com/bismuth-win-bi-bwb-special-discounts

**Comment by bitjson** [comment]
@BiWinBi please do not close and reopen pull requests – I edited your first message to link back to https://github.com/OpenTokenRegistry/otr.cash/pull/3.

This PR now includes `52094 insertions(+), 52077 deletions(-)`, I think from formatting issues. I pulled your changes, and I think this is what you're trying to add. **This description is still not up to our quality standards**:

```json
 "36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797": {
      "2023-05-29T05:00:00.000Z": {
        "name": "Bismuth Win Bi Token",
        "description": "Bismuth Win Bi Token serves as coupons and points on the e-commerce shop Bismuth Shed.\n\n The token has been created on May 15th 2023, with maximum supply of 21,000,000 BWBT, and divisible to 8 decimals.\n\n 10,000 BWBT is being offered for 0.01 BCH. This is equivalent to at least 1 USD and is backed by the team.\n\n At time of creation on mainnet, the token also existed on BNB and SmartBCH blockchain, as contract 0x2e1da8eb00cd1ff9b201f51e3705d87e06313881 on both. ",
        "token": {
          "category": "36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797",
          "decimals": 8,
          "symbol": "BWBT"
        },
        "uris": {
          "icon": "ipfs://bafkreib5fkmfd3frpjq7unumtj3ughcdxen4bcmmq3vqrp7bxzk626zeia",
          "web": "https://bismuthshed.com",
          "web": "https://biwinbi.github.io/web/",
          "chat": "https://t.me/BWBtothemoon"
        }
      }
    }
```


Just copying my relevant comments from https://github.com/OpenTokenRegistry/otr.cash/pull/3#issuecomment-1574316757:

> Thanks for your work on this @BiWinBi and @A60AB5450353F40E! The technical elements look solid; the description is already much clearer too!
> 
> > Bismuth Win Bi Token serves as coupons and points on the e-commerce shop Bismuth Shed.
> >
> > On Bitcoin Cash blockchain, the token has been created on May 15th 2023, with maximum supply of 21,000,000 BWBT, and divisible to 8 decimals.
> >
> > At time of creation on Bitcoin Cash network, the token also existed on BNB and SmartBCH blockchain, as contract 0x2e1da8eb00cd1ff9b201f51e3705d87e06313881 on both.
> 
> Initial questions:
> 
> - What does `Win Bi` mean or stand for? Given the description, it seems like users in the `en` locale would casually describe this as "Bismuth Shed points". Can you clarify the difference?
> - This is solely a fungible token category, correct? In what respect are they coupons? In what respect are they points? (What do the points do?) Do they map to some currency value? Is there some formula at which they convert, or some way a holder can otherwise understand the value of their token(s)? Are there legal terms posted on the website? Under what jurisdiction(s) are they enforced?
> - Is there some reason to mention the maximum supply? These are centrally issued/redeemed, right? So the unissued supply seems irrelevant, users should only plausibly care about circulating supply?
> - The description mentions assets issued on other chains: are those interchangeable? Deprecated, or in simultaneous use? Is there a method by which users can still exchange them? Are these details posted somewhere? (If so, a `uris.migrate` might be valuable!)


https://github.com/OpenTokenRegistry/otr.cash/pull/3#issuecomment-1592335231:

> Happy to review again, did you mean to push a commit with new changes to the description? The above questions don't seem to be resolved in the actual PR yet.
> 
> On content: please see the `Emerald DAO U23` entry for an example of an excellent description: `A series of 2000 keycard NFTs which entitle each holder to a unique, on-chain Emerald DAO safebox holding at least 0.101 BCH. [...]`. Notice that the description is asset-first, and succinctly describes the relevance to the end user. A [more complete reference is here](https://otr.cash/docs/list/#description).
> 
> As a general rule, most descriptions do not need to mention "CashTokens", "Bitcoin Cash Blockchain", or issuance details unless they are relevant to the user. (In this case, issuance is centralized and non-deterministic, so I think those details can be excluded?)
> 


And https://github.com/OpenTokenRegistry/otr.cash/pull/3#issuecomment-1597697312:

> Hi @BiWinBi, this listing looks technically ready, it just needs some clarification on the description ([these questions](https://github.com/OpenTokenRegistry/otr.cash/pull/3#issuecomment-1574316757)). 
> 
> Maybe it would be helpful for me to try to summarize as I understand from your posting above and the about page of your website?
> 
> A first draft:
> 
> `Loyalty points issued by Bismuth Shed, an e-commerce store specializing in bismuth crystals and ores.\n\nBismuth Shed was founded in 2017 and is based in Taipei City, Taiwan. Bismuth Shed also operates an open-air store at Taipei Nangang Exhibition Center.`
> 
> Is this accurate so far?
> 
> - I excluded discussion of CashTokens, creation date, and maximum supply, as those aren't relevant for a token issued and honored by a specific organization.
> - I also didn't mention the price at which you're selling points, since we generally want to keep this content "evergreen". 
> - I see you also mentioned `This is equivalent to at least 1 USD and is backed by the team.`. To make that sort of claim in this registry, we'd likely need to frame it in the context of a claim made by your auditor(s) rather than a claim of fact by OTR. For now, I just kept the description simple. 
> 
> Hopefully this gets you started, please let me know if I can help clarify anything! There's also [more guidance here on writing a great description](https://otr.cash/docs/list/#description).

Don't worry about making new commits to this PR. I'm very happy to do that for you.

**Just write the description you'd like to use as a comment in this PR**, and I can get your listing merged right away. If anything above is unclear, I recommend hiring someone or working with another volunteer to help you write a clear description.

**Comment by bitjson** [comment]
(Aside: @A60AB5450353F40E I haven't played with too much AI stuff but I think you have – is it reasonable now to design some long prompt or use some web service to have a LLM ask the user relevant questions and then draft a high-quality description?)

**Comment by BiWinBi** [comment]
Sure, thanks for your patience, @bitjson . 
You're really a great programmer and reviewer, no wonder the Cashtokens updates bring so much power to BCH.

 Here is the new description, please tell me which is still unclear.
 
 ```json
  "36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797": {
       "2023-05-29T05:00:00.000Z": {
         "name": "Bismuth Win Bi Token",
         "description": "Loyalty points issued by Bismuth Shed, an e-commerce store specializing in bismuth crystals and ores.\n\nBismuth Shed was founded in 2017 and is based in Taipei City, Taiwan. Bismuth Shed also offers pickup orders near MRT Taipei Nangang Exhibition Center Station.\n\n The token has been created on May 15th 2023.\n\n At time of creation on mainnet, the token also existed on BNB and SmartBCH blockchain, as contract 0x2e1da8eb00cd1ff9b201f51e3705d87e06313881 on both. "
,
         "token": {
           "category": "36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797",
           "decimals": 8,
           "symbol": "BWBT"
         },
         "uris": {
           "icon": "ipfs://bafkreib5fkmfd3frpjq7unumtj3ughcdxen4bcmmq3vqrp7bxzk626zeia",
           "web": "https://bismuthshed.com",
           "web": "https://biwinbi.github.io/web/",
           "chat": "https://t.me/BWBtothemoon"
         }
       }
     }
 ```

**Comment by bitjson** [comment]
@BiWinBi I'd like to get this merged – I resolved the merge conflicts and simplified the description to remove any claims that are hard for OTR to verify. Is this revision ok with you?

```json
"36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797": {
      "2023-05-29T05:00:00.000Z": {
        "name": "Bismuth Win Bi Token",
        "description": "Loyalty points issued by Bismuth Shed, an e-commerce store specializing in bismuth crystals and ores.",
        "token": {
          "category": "36546e4062a1cfd070a4a8d8ff9db18aae4ddf8d9ac9a4fa789314d108b49797",
          "decimals": 8,
          "symbol": "BWBT"
        },
        "uris": {
          "icon": "ipfs://bafkreib5fkmfd3frpjq7unumtj3ughcdxen4bcmmq3vqrp7bxzk626zeia",
          "web": "https://bismuthshed.com",
          "chat": "https://t.me/BWBtothemoon"
        }
      }
    }
```

I also noticed that your `web` uri, `https://bismuthshed.com`, seems to be down right now. Can you verify that this project is still active? If so, please let me know when the domain is responding again, and we can archive it and merge this PR.

**Comment by bitjson** [comment]
Closing due to inactivity. @BiWinBi, please let me know if you'd like me to re-open and merge this.

**Pull request closed without merging**
