### PR TITLE
add FLUFFY to otr

### PR DESCRIPTION
**Pull request by ghost**
# New Listing: `FLUFFY` 

- Identity Name: `FLUFFY`
- Authbase: `97026b156072d40cb4ef64303bde43539a6a72a66e7c78cd7e368d359645d368`

## Evidence Linking Authbase to Identity

- **Select one**:
  - [x] **Direct evidence**: a [chain-resolved registry](https://cashtokens.org/docs/bcmr/chip#chain-resolved-registries) at the authhead provides substantially equivalent metadata for this authbase. The Authhead TXID is provided below:
  - [ ] **Indirect evidence**: the identity is [burned](https://cashtokens.org/docs/bcmr/chip#burned-identities) or provably locked within a covenant, so the authbase can safely be linked using indirect evidence. Details and two or more corroborating, third party-archived URLs of reputable sources vouching for this association are provided below:

Authhead TXID: [67dd09e908fc4a96a563a7298e5f93a457da419e8611fcceaf807626ccd2eed2](https://explorer.bitcoinunlimited.info/tx/67dd09e908fc4a96a563a7298e5f93a457da419e8611fcceaf807626ccd2eed2)

## Evidence Linking Identity to Authbase

Archived URL(s):

## Evidence Linking Authbase to Categories

- **Select one**:
  - [x] Token `category` is equal to the authbase for all [Identity Snapshots](https://cashtokens.org/docs/bcmr/chip#identity-snapshots).
  - [ ] Evidence is provided for differing `category` values below:

## Substantiation of Other Claims

- **Select one**:
  - [x] The submission (esp. the `description`) includes no claims requiring substantiation.
  - [ ] The claims in this submission can be corroborated with the following evidence:

The FLUFFY token description reads:
I am part marshmallow, part dog.

The FLUFFY tokenId is displayed on official X https://x.com/fluffybch in the description.
# Checklist

- [x] I have reviewed the [OpenTokenRegistry inclusion criteria](https://otr.cash/docs/list#inclusion-criteria), and this listing can be included in the registry.
- [x] The listing completes all required fields:
  - **`name`**
    - [x] Objective, authoritative, and neutral tone
    - [x] No longer than 20 characters; exceptions may be allowed for existing legal names (please provide evidence above including the jurisdiction(s) in which the legal name is established).
  - **`description`**
    - [x] Objective, authoritative, and neutral tone
    - [x] Descriptions is appropriate for use in user interfaces without a disclaimer by unaffiliated, neutral, third parties (wallets, block explorers, exchanges, etc.); no exclamations, calls to action, or disputable statements.
    - [x] All claims are substantiated above.
  - **`token` information** (if applicable)
    - [x] Token `category` is defined.
    - [x] If fungible tokens exist for the `category`, `decimals` is defined.
    - **`symbol`**
      - [x] Globally-unique base symbol, including among assets not listed in OpenTokenRegistry.
      - [x] Valid symbol (regular expression: `/^[A-Z0-9]+[-A-Z0-9]*$/`)
      - [x] Appropriate minimum length (For new, primarily-fungible base symbols: minimum of 4 characters; non-fungible base symbols: minimum of 6 characters; see [Symbol Length Recommendations](https://cashtokens.org/docs/bcmr/chip/#symbol-length-recommendations))
      - [x] No longer than 13 characters for base symbols
      - [x] No longer than 26 characters for full symbols
  - **`uris.icon`**
    - [x] Uses IPFS with a v1 CID. To convert a v0 CID (begins with `Qm...`), try `dweb.link`. For example, `QmcNL1KcVmiDtwJe8WokrnzYeoHirsz1sNxNojncsxyb2p` is a v0 CID. It can be viewed at `https://dweb.link/ipfs/QmcNL1KcVmiDtwJe8WokrnzYeoHirsz1sNxNojncsxyb2p`, which redirects to a subdomain equal to the v1 CID: `https://bafybeigqogqx3n4cldk6nizl5vihopi2dkgvw4yqamc5rhleyqu25soe4e.ipfs.dweb.link/`. The correct URI for this icon is: `ipfs://bafybeigqogqx3n4cldk6nizl5vihopi2dkgvw4yqamc5rhleyqu25soe4e`.
    - [x] Either `SVG` format OR 400px by 400px `AVIF`, `WebP`, or `PNG`
  - **`uris.web`**
    - [x] Domain name is owned by the issuing project or organization
    - [x] Either `HTTPS` protocol OR ongoing activity demonstrated via optional URI identifiers (described in [Substantiation of Other Claims](#substantiation-of-other-claims))
  - [x] Includes relevant historical information in previous snapshots OR this token has never been rebranded, redenominated, or reissued
  - [x] All static data (images, animations, videos, binary files, etc.) uses `IPFS` with v1 CIDs to ensure file integrity (e.g. `ipfs://ba...`).

### CODE REVIEW

**Comment by georgedonnelly** [comment]
Hi, thanks for your PR. Have you reviewed the listing requirements? https://otr.cash/docs/list There are already several Fluffy coins out there and thus listing it here would go against the OTR listing requirements.

**Comment by ghost** [comment]
Hey George,
So of course you have your own requirments that needs to be met, but in the file [bitcoin-cash-metadata-registry.json] there is no other 'fluffy'. There are probably some fluffies on the other chains.
So basically let me know if I could have a 'first-mover' advantage on Bitcoin Cash network or if not - I will close the PR and that will be all.
Thanks!

**Comment by georgedonnelly** [comment]
Hi, I don't control this repo or your access to it. Just letting you know that the listing requirements likely don't favor your request. The final decision rests with @bitjson.

**Comment by ghost** [comment]
Okay, I fully understand that.
So let's wait for his decision.

**Comment by bitjson** [comment]
Thanks for opening a PR! Yes, as @georgedonnelly mentions, OTR can't assign you a ticker symbol; [the policy is here](https://otr.cash/docs/list#symbol):

> ### Symbol
> 
> **All asset symbols included in OpenTokenRegistry must be globally unique**, including among assets not listed in OpenTokenRegistry. For new assets, we recommend reviewing the [BCMR Symbol Length Recommendations](https://cashtokens.org/docs/bcmr/chip#symbol-length-recommendations).
> 
> OpenTokenRegistry has no control over symbol "assignments" in the wider marketplace; we do not have the power to unilaterally grant contested symbols to any particular party. Neutral wallets, exchanges, block explorers, and other service providers rely on OpenTokenRegistry to safeguard the symbols and data they render to users, so adding new listings which conflict with existing asset symbols in the wider marketplace might prevent others from relying on OpenTokenRegistry's data.
> 
> In cases of long-standing disputes over a particular symbol (e.g. the same symbol has been used to refer to different assets by good-faith actors across multiple international markets), OpenTokenRegistry may be forced to prefix one or both symbols for clarity, e.g. `NYSE-DTE`, `XETRA-DTE`.
> 
> If selecting a non-contentious symbol is impossible, please provide multiple examples of well-known, neutral institutions which recognize this asset using the contentious symbol (e.g. exchanges, brokers, custodians, data providers, etc.) and indicate a preferred prefix for the listing in OpenTokenRegistry (e.g. `NYSE-`, `NASDAQ-`, `XETRA-`, `PAR-`, etc.).

If the token is known in some venue as `FLUFFY`, please submit your PR with an appropriate prefix to disambiguate.

**Comment by georgedonnelly** [comment]
Perhaps BCHFLUFFY?

**Comment by ghost** [comment]
Thanks guys for your input, without opening this PR I wouldn't even think about this stuff.
So I would need to change the token symbol from 'FLUFFY' to e.g. 'BCHFLUFFY' in order to comply with the rules? Do I understand it in the correct way?

**Comment by georgedonnelly** [comment]
Your ticker should be globally unique if you want it considered for inclusion in the OTR. As well, it must comply with all of the other listing requirements as we linked you above. Of course, you may choose to not include your token in the OTR, if you so decide. But these are the listing requirements for the OTR. Hope that helps. :)

**Comment by ghost** [comment]
Yes, I understand it, thanks.
As of now - I will close the PR.

**Pull request closed without merging**
